/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.AtletaControl;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import static jdk.internal.joptsimple.internal.Messages.message;
import model.Atleta;

/**
 *
 * @author aluno
 */
public class FrmBusca extends javax.swing.JFrame {
    
    private AtletaControl atletaControl = new AtletaControl();
    private ArrayList<Atleta> atletasListados = new ArrayList();
    
    /**
     * Creates new form FrmBusca
     */
    public FrmBusca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxTipoBusca = new javax.swing.JComboBox<>();
        lblTipoBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        lblBusca = new javax.swing.JLabel();
        btnBusca = new javax.swing.JButton();
        btnMostrarTodosCadastros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBusca = new javax.swing.JList<>();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboBoxTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código", "Idade", "Altura", "Peso" }));

        lblTipoBusca.setText("Buscar por: ");

        lblBusca.setText("Busca: ");

        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnMostrarTodosCadastros.setText("Exibir todos cadastrados");
        btnMostrarTodosCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosCadastrosActionPerformed(evt);
            }
        });

        jListBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListBuscaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListBusca);

        btnExcluir.setText("Excluir Selecionado");
        btnExcluir.setToolTipText("");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTipoBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusca))
                            .addComponent(btnBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarTodosCadastros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoBusca)
                    .addComponent(comboBoxTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarTodosCadastros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusca)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarTodosCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosCadastrosActionPerformed
        
        jListBusca.setModel(new DefaultListModel());
        atletasListados = new ArrayList();
        
        DefaultListModel stringLista = new DefaultListModel();
        String tempBuf;
        
        for(Atleta a:AtletaControl.getListaAtletas()) {
            tempBuf = "ID " + a.getCodigo() + ": " + a.getNome() + ", " + a.getIdade() + " anos";
            stringLista.addElement(tempBuf);
        }
        
        jListBusca.setModel(stringLista);
        atletasListados = AtletaControl.getListaAtletas();
    }//GEN-LAST:event_btnMostrarTodosCadastrosActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        DefaultListModel stringLista = new DefaultListModel();
        ArrayList<Atleta> resultadoBusca = null;
        
        jListBusca.setModel(new DefaultListModel());
        atletasListados = new ArrayList();
        
        String tempBuf;
        
        try{
            if(comboBoxTipoBusca.getSelectedIndex() == 0){
                resultadoBusca = atletaControl.getAtletaPorNome(txtBusca.getText());
                
            }else if(comboBoxTipoBusca.getSelectedIndex() == 1){
                resultadoBusca = atletaControl.getAtletaPorCodigo(Integer.parseInt(txtBusca.getText()));
                
            }else if(comboBoxTipoBusca.getSelectedIndex() == 2){
                resultadoBusca = atletaControl.getAtletaPorIdade(Integer.parseInt(txtBusca.getText()));
                
            }else if(comboBoxTipoBusca.getSelectedIndex() == 3){
                resultadoBusca = atletaControl.getAtletaPorAltura(Integer.parseInt(txtBusca.getText()));
                
            }else if(comboBoxTipoBusca.getSelectedIndex() == 4){
                resultadoBusca = atletaControl.getAtletaPorPeso(Double.parseDouble(txtBusca.getText()));
            }
            
            for(Atleta a: resultadoBusca){
                
                tempBuf = "ID " + a.getCodigo() + ": " + a.getNome() + ", " + a.getIdade() + " anos";
                stringLista.addElement(tempBuf);
            }
            
            jListBusca.setModel(stringLista);
            atletasListados = resultadoBusca;
            
        }catch(NullPointerException e){
            
            JOptionPane.showMessageDialog(null, "Não há usuários com tais dados!");
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void jListBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListBuscaMouseClicked
        String outputString = "";
        JList list = (JList)evt.getSource();
        
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            
            outputString += "Nome: " + atletasListados.get(index).getNome();
            outputString += "\nPeso: " + atletasListados.get(index).getPeso() + "kg";
            outputString += "\nAltura: " + atletasListados.get(index).getAltura() + "cm";
            outputString += "\nIdade: " + atletasListados.get(index).getIdade() + " anos";
            outputString += "\nCódigo: " + atletasListados.get(index).getCodigo();
            
            JOptionPane.showMessageDialog(null, outputString);
        }
    }//GEN-LAST:event_jListBuscaMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        DefaultListModel stringLista = new DefaultListModel();        
        String tempBuf;

        
        try {
            tempBuf = "\n\nNome: " + atletasListados.get(jListBusca.getSelectedIndex()).getNome();
            tempBuf += "\nCódigo: " + atletasListados.get(jListBusca.getSelectedIndex()).getCodigo();
            tempBuf += "\nPeso: " + atletasListados.get(jListBusca.getSelectedIndex()).getPeso();
            tempBuf += "\nAltura: " + atletasListados.get(jListBusca.getSelectedIndex()).getAltura();
            tempBuf += "\nIdade: " + atletasListados.get(jListBusca.getSelectedIndex()).getIdade();
            
            
            int confirmar = JOptionPane.showOptionDialog(null, "Deseja realmente excluir este usuário?: " + tempBuf, "Excluir?",
              JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, "No");
            
            if(confirmar == JOptionPane.YES_OPTION) {
                atletaControl.excluirAtleta(atletasListados.get(jListBusca.getSelectedIndex()));
                JOptionPane.showMessageDialog(null, "Atleta excluído!");
            } else {
                JOptionPane.showMessageDialog(null, "Atleta não excluído.");
                return;
            }
            
        
        
            for(Atleta a: atletasListados){
                
                tempBuf = "ID " + a.getCodigo() + ": " + a.getNome() + ", " + a.getIdade() + " anos";
                stringLista.addElement(tempBuf);
            }
            
            jListBusca.setModel(stringLista);
            
        } catch(NumberFormatException | IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Não há usuários selecionados!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBusca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMostrarTodosCadastros;
    private javax.swing.JComboBox<String> comboBoxTipoBusca;
    private javax.swing.JList<String> jListBusca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblTipoBusca;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
